### ISSUE TITLE
python conflicts

### ISSUE THREAD

**Issue by cnd** [aclex/pytorch-ebuild#8] opened 2020-03-05 12:45 UTC
what's that:

```
emerge: there are no ebuilds built with USE flags to satisfy "dev-python/typing[python_targets_python3_7(-)?,-python_single_target_python3_7(-)]".
!!! One of the following packages is required to complete your request:
- sci-libs/pytorch-1.4.0::aclex-pytorch (Change USE: -python_targets_python3_7, this change violates use flag constraints defined by sci-libs/pytorch-1.4.0: 'python? ( any-of ( python_targets_python3_7 ) ) numpy? ( python ) atlas? ( !eigen !mkl !openblas ) eigen? ( !atlas !mkl !openblas ) mkl? ( !atlas !eigen !openblas ) openblas? ( !atlas !eigen !mkl ) rocm? ( !mkldnn !cuda )')
(dependency required by "sci-libs/pytorch-1.4.0::aclex-pytorch" [ebuild])
(dependency required by "=pytorch-1.4.0" [argument])
```

hi

**Comment by aclex** [comment] 2020-03-05 12:57
Hi @cnd, yes, it seems to be a bug in the ebuild, `dev-python/typing` seems to be merged to Python in version 3, so no need in this dependency. I'll fix it later today in the evening. Thank you for reporting!

**Comment by cnd** [comment] 2020-03-05 13:00
ah I see, thank you for pointing that.

**Comment by cnd** [comment] 2020-03-05 13:05
@aclex  * Fetching https://github.com/pytorch/pytorch ...
git fetch https://github.com/pytorch/pytorch +refs/heads/v1.4.0:refs/heads/v1.4.0
fatal: couldn't find remote ref refs/heads/v1.4.0
 * ERROR: sci-libs/pytorch-1.4.0::aclex-pytorch failed (unpack phase):
 *   Unable to fetch from any of EGIT_REPO_URI

**Comment by cnd** [comment] 2020-03-05 13:06
gh... I was trying ebuild from sci overlay however there I get some error about caffe :: something not being template

**Comment by aclex** [comment] 2020-03-05 13:17
@cnd oh, quite strange, haven't changed this part for quite some time already. Reproducible for me, though. Can't look at it closer now, so will try to fix it a little later. Maybe, something is broken in `git-r3.eclass` after recent portage update.

**Comment by aclex** [comment] 2020-03-05 13:21
@cnd sorry, no, that's my fault, there apparently should be `EGIT_COMMIT` instead of `EGIT_BRANCH` in the ebuild to address a tag version. There used to be a branch with the same name, which was obviously removed recently. Will fix it as well later today.

**Comment by cnd** [comment] 2020-03-05 13:22
okay, trying

**Comment by cnd** [comment] 2020-03-05 14:10
again errors with Caffe

```
In file included from /var/tmp/portage/sci-libs/pytorch-1.4.0/work/pytorch-1.4.0/caffe2/contrib/opencl/context.cc:1:
/var/tmp/portage/sci-libs/pytorch-1.4.0/work/pytorch-1.4.0/cmake/../caffe2/contrib/opencl/context.h:69:21: warning: comparison of integers of different signs: 'int' and 'std::vector::size_type' (aka 'unsigned long') [-Wsign-compare]
    CAFFE_ENFORCE(a < ctx.devices.size());
                  ~ ^ ~~~~~~~~~~~~~~~~~~
/var/tmp/portage/sci-libs/pytorch-1.4.0/work/pytorch-1.4.0/c10/util/Logging.h:96:24: note: expanded from macro 'CAFFE_ENFORCE'
    if (C10_UNLIKELY(!(condition))) {                               \
                       ^~~~~~~~~
/var/tmp/portage/sci-libs/pytorch-1.4.0/work/pytorch-1.4.0/c10/macros/Macros.h:140:65: note: expanded from macro 'C10_UNLIKELY'
#define C10_UNLIKELY(expr)  (__builtin_expect(static_cast<bool>(expr), 0))
                                                                ^~~~
/var/tmp/portage/sci-libs/pytorch-1.4.0/work/pytorch-1.4.0/caffe2/contrib/opencl/context.cc:10:24: error: expected '>'
CAFFE_KNOWN_TYPE(Tensor<OpenCLContext>);
                       ^
```

**Comment by aclex** [comment] 2020-03-05 14:23
@cnd what's your compiler and its version? Seems to be more strict one, than the targeted by the upstream. This is pretty much expected with every new version, unfortunately.

**Comment by cnd** [comment] 2020-03-05 14:28
gcc (Gentoo 9.2.0-r4 p5) 9.2.0

**Comment by cnd** [comment] 2020-03-05 14:33
more feels like some OpenCL upstream bug

**Comment by aclex** [comment] 2020-03-05 14:36
Hmm... strange. @heroxbd mentioned, that at least the version in sci overlay compiles successfully with this exact version. The 1.4.0 ebuild here forcefully sets `clang` as a compiler due to another regression in GCC 9. Maybe yes, some changes in the code still happened.

**Comment by aclex** [comment] 2020-03-05 21:26
@cnd I've just pushed the changes we discussed and also tried the recent 1.4.0 ebuild — compiles for me in the 'out of the box' version. my USE flags are: `-doc fbgemm ffmpeg gflags glog leveldb lmdb mkldnn namedtensor numpy openblas observers qnnpack -rocm tbb -test zeromq` Maybe something here?

**Comment by cnd** [comment] 2020-03-06 06:11
@aclex try with opencl use flag

**Comment by aclex** [comment] 2020-03-06 06:34
@cnd aa, OK, forgot you've mentioned it.

**Closed** 2021-12-09 09:26 UTC
